Fix illegal fragment error for Privacy Guard
Fixes the following error:

FATAL EXCEPTION: main

Process: com.android.settings, PID: 3151

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.oct.tentacles.SettingsActivity}: java.lang.IllegalArgumentException: Invalid fragment for this activity: com.android.settings.applications.AppOpsDetails

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2224)

	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2274)

	at android.app.ActivityThread.access$800(ActivityThread.java:142)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)

	at android.os.Handler.dispatchMessage(Handler.java:102)

	at android.os.Looper.loop(Looper.java:136)

	at android.app.ActivityThread.main(ActivityThread.java:5062)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:515)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)

	at dalvik.system.NativeStart.main(Native Method)

Caused by: java.lang.IllegalArgumentException: Invalid fragment for this activity: com.android.settings.applications.AppOpsDetails

	at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1180)

	at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1199)

	at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:545)

	at com.oct.tentacles.SettingsActivity.onCreate(SettingsActivity.java:78)

	at android.app.Activity.performCreate(Activity.java:6041)

	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)

	... 11 more

Conflicts:
	AndroidManifest.xml
	src/com/oct/tentacles/SettingsActivity.java